name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Tests
        run: pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_DIGITAL_OCEAN }}
      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no root@104.248.249.218 <<EOF
          cd /home/farm/
          rm -f main.py
          eval "$(ssh-agent -s)"
          ssh-add - <<< "$SSH_PRIVATE_KEY"
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git clone git@github.com:<github_username>/<repo_name>.git .
          systemctl restart farm
          EOF

